# Mod04 Using NumPy Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.16.5'

## NumPy indexing and slicing

In [3]:
# print entire array, element 0, element 1, last element.
ar = np.arange(5); print(ar); ar[0], ar[1], ar[-1]

[0 1 2 3 4]


(0, 1, 4)

In [4]:
# 2nd, last and 1st elements
ar=np.arange(5); ar[1], ar[-1], ar[0]

(1, 4, 0)

In [5]:
# Reverse array using ::-1 idiom
ar=np.arange(5); ar[::-1]

array([4, 3, 2, 1, 0])

In [6]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [7]:
ar[1,1]

8

In [8]:
ar[1,1]=5; ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 13]])

In [9]:
# Retrieve row 2
ar[2]

array([11, 12, 13])

In [10]:
ar[2,:]

array([11, 12, 13])

In [11]:
# Retrieve column 1
ar[:,1]

array([ 3,  5, 12])

In [12]:
# Python list style, poor performance
%timeit ar[2][1]

183 ns ± 4.12 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [13]:
# NumPy tuple style, better performance
%timeit ar[2,1]

93.8 ns ± 3.99 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


##  Array slicing
Arrays can be sliced using the following syntax:<br>
ar[startIndex: endIndex: stepValue].

In [14]:
ar=2*np.arange(6); ar

array([ 0,  2,  4,  6,  8, 10])

In [15]:
ar[1:5:2]

array([2, 6])

In [16]:
# if we wish to include the endIndex value, we need to go above it
ar[1:6:2] 

array([ 2,  6, 10])

In [17]:
ar[:4]

array([0, 2, 4, 6])

In [18]:
ar[4:]

array([ 8, 10])

In [19]:
# Slice array with stepValue=3
ar[::3]

array([0, 6])

Assignment and slicing can be combined as shown in the following code snippet:

In [20]:
ar

array([ 0,  2,  4,  6,  8, 10])

In [21]:
ar[:3]=1; ar

array([ 1,  1,  1,  6,  8, 10])

In [22]:
ar[2:]=np.ones(4);ar

array([1, 1, 1, 1, 1, 1])

## Illustrate the scope of indexing in NumPy
![](figures/2.2-numpy_indexing.png)

In [23]:
#%%timeit
a=np.zeros((6,6),dtype=np.int32)
ar=np.arange(6)
for i in range(6):
    a[i]=ar+i*10

In [24]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [25]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

### Fancy Indexing

In [26]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [27]:
# access three different elements
[x[3], x[7], x[2]]

[71, 86, 14]

In [28]:
# pass a single list or array of indices to obtain the same result
ind = [3, 7, 2]
x[ind]

array([71, 86, 14])

In [29]:
x[[3,7,2]]

array([71, 86, 14])

#### Access rows in 2d array

In [30]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

In [31]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [32]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [33]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [34]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

## Array masking

In [36]:
np.random.seed(10)
ar=np.random.randint(0,25,10); ar

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [37]:
evenMask=(ar % 2==0); evenMask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [38]:
evenNums=ar[evenMask]; evenNums

array([ 4,  0, 16,  8,  0])

To eliminate missing values

In [39]:
ar=np.array(['Hungary','Nigeria',
'Guatemala','','Poland','','Japan']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='<U9')

In [40]:
ar[ar=='']='USA'; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='<U9')

Arrays of integers can be used to index an array to produce another array

In [41]:
ar=11*np.arange(0,10); ar

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [42]:
ar[[1,3,4,2,7]]

array([11, 33, 44, 22, 77])

In [43]:
ar[1,3,4,2,7]

IndexError: too many indices for array

Assignment is also possible with array indexing

In [44]:
ar[[1,3]]=50; ar

array([ 0, 50, 22, 50, 44, 55, 66, 77, 88, 99])

Get Someones data

In [45]:
# every row of data corresponding to index of names
np.random.seed(20)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [46]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [47]:
data

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644]])

In [48]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [49]:
data[names=='Bob']

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517]])

## Copies and views

<b>Modifying view modifies original array</b>

In [50]:
ar1=np.arange(12); ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
ar2=ar1[::2]; ar2

array([ 0,  2,  4,  6,  8, 10])

In [52]:
ar2[1]=-1; ar1

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

<b>Use np.copy to force a copy</b><br>

In [53]:
ar=np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
arc=ar[:3].copy(); arc

array([0, 1, 2])

In [55]:
arc[0]=-1; arc

array([-1,  1,  2])

In [56]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

another example

In [57]:
np.random.seed(0)
x = np.random.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [58]:
x_sub = x[:2, :2]
x_sub

array([[5, 0],
       [7, 9]])

In [59]:
x_sub[0, 0] = 99
x

array([[99,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])